export const LOCAL_STORAGE_KEY = "user_token";

export const UserContextConstants = {
    SET_USER: "SET_USER",
    SET_CHAR_PER_REQUSET: "SET_CHAR_PER_REQUSET",
    SET_CHAR_PER_MONTH: "SET_CHAR_PER_MONTH",
    SET_MESSAGE: "SET_MESSAGE",
    SET_LOADING_OVERLAY: "SET_LOADING_OVERLAY",
    SET_PREMIUM_ID: "SET_PREMIUM_ID",
}

export const AudioContextConstants = {
    SET_AUDIO_INFO: "SET_AUDIO_INFO",
    SET_LINK_AUDIO: "SET_LINK_AUDIO",
    SET_IS_PLAY: "SET_IS_PLAY",
    SET_LIST_HISTORY_AUDIOS: "SET_LIST_HISTORY_AUDIOS",
}